name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 2"
    
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test in Ubuntu
        run: ./test.sh ubuntu
  test-ubuntu-14-04:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test in Ubuntu 14.04
        run: ./test.sh ubuntu-14.04      
  test-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test in Alpine
        run: ./test.sh alpine
  test-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test in Debian
        run: ./test.sh debian
  test-amazonlinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test in Amazonlinux
        run: ./test.sh amazonlinux
